# Generated by Django 6.0.4 on 2026-06-09 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studymode'),
        ('students', '0014_religion_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PROMOTE', 'Promoted / ترقية'), ('RETAIN', 'Retained / إعادة'), ('TRANSFER_OUT', 'Transferred Out / منقول خارجاً')], default='PROMOTE', max_length=15)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('from_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_from_year', to='core.academicyear')),
                ('from_division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_from_division', to='core.division')),
                ('from_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_from_grade', to='core.grade')),
                ('from_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_from_section', to='core.section')),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_done', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_history', to='students.student')),
                ('to_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_to_year', to='core.academicyear')),
                ('to_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_to_division', to='core.division')),
                ('to_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_to_grade', to='core.grade')),
                ('to_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_to_section', to='core.section')),
            ],
            options={
                'verbose_name': 'Promotion History / سجل الترقية',
                'ordering': ['-promoted_at'],
                'indexes': [models.Index(fields=['student', '-promoted_at'], name='promo_student_idx'), models.Index(fields=['to_academic_year'], name='promo_to_year_idx')],
            },
        ),
    ]
