# Generated by Django 6.0.4 on 2026-06-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_promotionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees_contact_email',
            field=models.EmailField(blank=True, help_text='Email used for fee reminders. Leave blank to use father → mother → guardian.', max_length=254, verbose_name='Fees Contact Email / بريد للرسوم'),
        ),
        migrations.AddField(
            model_name='student',
            name='fees_contact_phone',
            field=models.CharField(blank=True, help_text='Phone used for fee reminders (WhatsApp). Leave blank to use father → mother → guardian.', max_length=20, verbose_name='Fees Contact Phone / هاتف للرسوم'),
        ),
    ]
