# Generated by Django 6.0.4 on 2026-06-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0037_rename_installments_to_semesters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionfeeconfig',
            name='num_payments',
            field=models.PositiveSmallIntegerField(choices=[(2, '2 Payments (1 per semester)'), (3, '3 Payments (2 in Semester 1, 1 in Semester 2)')], default=2, verbose_name='Number of Installments'),
        ),
        migrations.AlterField(
            model_name='tuitioninstallment',
            name='installment_type',
            field=models.CharField(choices=[('RESERVATION', 'Reservation / Down Payment'), ('FIRST', '1st Payment'), ('SECOND', '2nd Payment'), ('THIRD', '3rd Payment')], max_length=15),
        ),
    ]
